CREATE TABLE perfils (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   nome VARCHAR(30) NOT NULL,
   CONSTRAINT pk_perfils PRIMARY KEY (id)
);

CREATE TABLE pontos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   usuario_id INTEGER,
   rifa_id BIGINT,
   ponto VARCHAR(10) NOT NULL,
   valor DECIMAL(10, 2) NOT NULL,
   ponto_escolhido BOOLEAN NOT NULL,
   data_criacao TIMESTAMP WITHOUT TIME ZONE,
   data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_pontos PRIMARY KEY (id)
);

CREATE TABLE rifas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   data_criacao TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
   data_sorteio TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   descricao VARCHAR(255) NOT NULL,
   titulo VARCHAR(50) NOT NULL,
   imagem VARCHAR(255),
   quantidade_ponto INTEGER NOT NULL,
   valor DECIMAL(10, 2) NOT NULL,
   tipo_rifa VARCHAR(50),
   usuario_id INTEGER NOT NULL,
   CONSTRAINT pk_rifas PRIMARY KEY (id)
);

CREATE TABLE usuario_perfil (
  perfil_id INTEGER NOT NULL,
   usuario_id INTEGER NOT NULL,
   CONSTRAINT pk_usuario_perfil PRIMARY KEY (perfil_id, usuario_id)
);

CREATE TABLE usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   nome VARCHAR(100) NOT NULL,
   email VARCHAR(100) NOT NULL,
   senha VARCHAR(255) NOT NULL,
   data_criacao TIMESTAMP WITHOUT TIME ZONE,
   data_atualizacao TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

ALTER TABLE usuarios ADD CONSTRAINT uc_usuarios_email UNIQUE (email);

ALTER TABLE pontos ADD CONSTRAINT FK_PONTOS_ON_RIFA FOREIGN KEY (rifa_id) REFERENCES rifas (id);

ALTER TABLE pontos ADD CONSTRAINT FK_PONTOS_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuarios (id);

ALTER TABLE rifas ADD CONSTRAINT FK_RIFAS_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuarios (id);

ALTER TABLE usuario_perfil ADD CONSTRAINT fk_usuper_on_perfil FOREIGN KEY (perfil_id) REFERENCES perfils (id);

ALTER TABLE usuario_perfil ADD CONSTRAINT fk_usuper_on_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id);